// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFPUAWSX-ZXWcOZVI6-tm0MaF9YiO4pU',
    appId: '1:987763082270:web:cc63a6eef03e7d51d4da0f',
    messagingSenderId: '987763082270',
    projectId: 'team-up-game-a6449',
    authDomain: 'team-up-game-a6449.firebaseapp.com',
    storageBucket: 'team-up-game-a6449.firebasestorage.app',
    measurementId: 'G-ZB4402QS80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIxaHsjQBSRFxwCIaMn0KEy-NMbT3u_Ww',
    appId: '1:987763082270:android:894942f41c014819d4da0f',
    messagingSenderId: '987763082270',
    projectId: 'team-up-game-a6449',
    storageBucket: 'team-up-game-a6449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvd0hVlqi4SNInZiIWzQJgNZctpiTQDb4',
    appId: '1:987763082270:ios:4fc4cbbe3325517ad4da0f',
    messagingSenderId: '987763082270',
    projectId: 'team-up-game-a6449',
    storageBucket: 'team-up-game-a6449.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvd0hVlqi4SNInZiIWzQJgNZctpiTQDb4',
    appId: '1:987763082270:ios:4fc4cbbe3325517ad4da0f',
    messagingSenderId: '987763082270',
    projectId: 'team-up-game-a6449',
    storageBucket: 'team-up-game-a6449.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFPUAWSX-ZXWcOZVI6-tm0MaF9YiO4pU',
    appId: '1:987763082270:web:e868094a1c2f8807d4da0f',
    messagingSenderId: '987763082270',
    projectId: 'team-up-game-a6449',
    authDomain: 'team-up-game-a6449.firebaseapp.com',
    storageBucket: 'team-up-game-a6449.firebasestorage.app',
    measurementId: 'G-K5ZP5JNSMQ',
  );
}
